PUT http://localhost:3003/api/blogs/5f5dc3860e8da5010458e541
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxhcyIsImlkIjoiNWY0NzA3YjNhNWQyZDQwZGFjY2NmZTg3IiwiaWF0IjoxNjAxMjk5Nzc4fQ.G4do6gn95DP0hMv3yQ8x4-mQpjDEYxXjpwkGPWPTEDs

{
    "author": "OH GIGI"
}